# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/dzj0489/Desktop/fffff/project/darksoul/fpga/darksoul/darksoul.runs/synth_1/soc_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param simulator.modelsimInstallPath E:/modelsim/win64
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/dzj0489/Desktop/fffff/project/darksoul/fpga/darksoul/darksoul.cache/wt [current_project]
set_property parent.project_path C:/Users/dzj0489/Desktop/fffff/project/darksoul/fpga/darksoul/darksoul.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/dzj0489/Desktop/fffff/project/darksoul/fpga/darksoul/darksoul.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files c:/Users/dzj0489/Desktop/fffff/project/darksoul/fpga/darksoul/darksoul.srcs/sources_1/ip/blk_mem_gen_0/sram_init.coe
read_verilog -library xil_defaultlib {
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/utils/AXI2SRAM.v
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/core/LCA.v
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/core/defines.v
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/core/agu.v
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/core/alu.v
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/soc/axi_xbar.v
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/core/bju.v
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/core/booth_encoder.v
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/core/bus_if.v
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/perips/clint.v
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/core/compressor.v
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/core/cpu_top.v
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/core/csr.v
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/core/csru.v
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/core/decoder.v
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/core/div.v
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/core/ex_mem.v
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/core/ex_stage.v
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/core/id_ex.v
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/core/id_stage.v
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/core/if_id.v
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/core/if_stage.v
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/core/imm_gen.v
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/core/mem_stage.v
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/core/mem_wb.v
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/core/mul.v
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/core/mux_alu.v
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/core/pc_reg.v
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/core/pipe_ctrl.v
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/core/pp_gen.v
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/core/regfile.v
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/core/wallace_tree.v
  C:/Users/dzj0489/Desktop/fffff/project/darksoul/rtl/soc/soc_top.v
}
read_ip -quiet C:/Users/dzj0489/Desktop/fffff/project/darksoul/fpga/darksoul/darksoul.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all c:/Users/dzj0489/Desktop/fffff/project/darksoul/fpga/darksoul/darksoul.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top soc_top -part xc7a35tfgg484-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file soc_top_utilization_synth.rpt -pb soc_top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
