######################################################################
#
# File name : cpu_tb_compile.do
# Created on: Sat Feb 01 17:36:03 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
E:\\modelsim\\win64\\vlib modelsim_lib/work
E:\\modelsim\\win64\\vlib modelsim_lib/msim

E:\\modelsim\\win64\\vlib modelsim_lib/msim/xil_defaultlib

E:\\modelsim\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

E:\\modelsim\\win64\\vlog  -incr -mfcu -work xil_defaultlib  \
"../../../../darksoul.gen/sources_1/ip/blk_mem_gen_0/sim/blk_mem_gen_0.v" \
"../../../../../../rtl/utils/AXI2SRAM.v" \
"../../../../../../rtl/core/LCA.v" \
"../../../../../../rtl/core/agu.v" \
"../../../../../../rtl/core/alu.v" \
"../../../../../../rtl/soc/axi_xbar.v" \
"../../../../../../rtl/core/bju.v" \
"../../../../../../rtl/core/booth_encoder.v" \
"../../../../../../rtl/core/bus_if.v" \
"../../../../../../rtl/perips/clint.v" \
"../../../../../../rtl/core/compressor.v" \
"../../../../../../rtl/core/cpu_top.v" \
"../../../../../../rtl/core/csr.v" \
"../../../../../../rtl/core/csru.v" \
"../../../../../../rtl/core/decoder.v" \
"../../../../../../rtl/core/div.v" \
"../../../../../../rtl/core/ex_mem.v" \
"../../../../../../rtl/core/ex_stage.v" \
"../../../../../../rtl/core/id_ex.v" \
"../../../../../../rtl/core/id_stage.v" \
"../../../../../../rtl/core/if_id.v" \
"../../../../../../rtl/core/if_stage.v" \
"../../../../../../rtl/core/imm_gen.v" \
"../../../../../../rtl/core/mem_stage.v" \
"../../../../../../rtl/core/mem_wb.v" \
"../../../../../../rtl/core/mul.v" \
"../../../../../../rtl/core/mux_alu.v" \
"../../../../../../rtl/core/pc_reg.v" \
"../../../../../../rtl/core/pipe_ctrl.v" \
"../../../../../../rtl/core/pp_gen.v" \
"../../../../../../rtl/core/regfile.v" \
"../../../../../../rtl/soc/soc_top.v" \
"../../../../../../rtl/core/wallace_tree.v" \
"../../../../../../tb/cpu_tb.v" \


# compile glbl module
E:\\modelsim\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

