######################################################################
#
# File name : cpu_tb_wave.do
# Created on: Sat Feb 01 15:09:43 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
