######################################################################
#
# File name : cpu_tb_simulate.do
# Created on: Sat Feb 01 17:36:05 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L blk_mem_gen_v8_4_5 -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.cpu_tb xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {cpu_tb_wave.do}

view wave
view structure
view signals

do {cpu_tb.udo}

run 1000ns
